//! Raw FFI bindings to `libfuji.dylib`.
#![allow(rustdoc::broken_intra_doc_links)]
//!
//! # Safety
//! All `extern "C"` functions are `unsafe`. Use the [`fuji`] crate for a safe API.
//!
//! # Linking
//! Requires `libfuji.dylib` on `DYLD_LIBRARY_PATH`, `@rpath`, or adjacent to the binary.
//! The [`build.rs`](build.rs) emits `cargo:rustc-link-search=..` so the linker finds the dylib
//! in the project root.

#![allow(non_camel_case_types, non_snake_case)]

use std::os::raw::c_char;

/// Curve selector: `FUJI_CURVE_PALLAS (0)` or `FUJI_CURVE_VESTA (1)`.
pub type fuji_curve = i32;

/// Pallas curve. Base field modulus `0x4000...0001`, scalar field is the Vesta modulus.
pub const FUJI_CURVE_PALLAS: fuji_curve = 0;

/// Vesta curve. Base field modulus is the Pallas scalar field; forms a 2-cycle with Pallas.
pub const FUJI_CURVE_VESTA: fuji_curve = 1;

/// Success.
pub const FUJI_OK: i32 = 0;

/// AMX coprocessor is not available (e.g. Intel Mac or VM). Fallback code was used.
pub const FUJI_ERR_AMX: i32 = -2;

/// Memory allocation failed (calloc returned NULL).
pub const FUJI_ERR_OOM: i32 = -3;

/// Invalid context: a required pointer argument was NULL or an MSM stream was not initialized.
pub const FUJI_ERR_CTX: i32 = -4;

/// 32-byte (255-bit) field element in canonical little-endian byte representation.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct fuji_field {
    pub limbs: [u8; 32],
}

/// Affine elliptic curve point `(x, y)` satisfying `y² = x³ + 5` over a Pasta field.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct fuji_affine {
    pub x: fuji_field,
    pub y: fuji_field,
}

/// Jacobian projective point `(X, Y, Z)` with `z = 0` representing the identity.
/// Affine coordinates: `x = X/Z²`, `y = Y/Z³`.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct fuji_point {
    pub x: fuji_field,
    pub y: fuji_field,
    pub z: fuji_field,
}

/// Opaque handle for a streaming MSM state machine. Created by [`fuji_msm_stream_new`],
/// fed by [`fuji_msm_stream_feed`], consumed by [`fuji_msm_stream_finalize`].
pub enum fuji_msm_stream {}

/// Opaque handle for precomputed SRS data.
pub enum fuji_srs_ctx {}

/// Deserialized bytecode (matches fuji_bytecode in bytecode.h).
#[repr(C)]
pub struct fuji_bytecode {
    pub code: *mut fuji_eval_instr,
    pub n_instr: i32,
    pub poly_table: *mut fuji_eval_poly,
    pub n_polys: i32,
    pub poly_data: *mut fuji_field,
    pub poly_offsets: *mut i32,
    pub scalars: *mut fuji_field,
    pub n_scalars: i32,
    pub omega: *mut fuji_field,
    pub curve: i32,
    pub chunk_len: i32,
    pub max_depth: i32,
    pub _block: *mut std::ffi::c_void,
}

// ── Flat instruction evaluator types ──

/// Compiled instruction (matches fuji_eval_instr in eval.h).
#[repr(C)]
pub struct fuji_eval_instr {
    pub opcode: i32,
    pub arg0: i32,
    pub arg1: i32,
}

/// Polynomial column entry (matches fuji_eval_poly in eval.h).
#[repr(C)]
pub struct fuji_eval_poly {
    pub data: *const fuji_field,
    pub domain_size: i32,
}

/// JIT benchmark results (matches fuji_jit_bench_t in jit.h).
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct fuji_jit_bench_t {
    pub compile_ms: f64,
    pub exec_ms: f64,
    pub seq_ms: f64,
    pub match_: i32,       // named match_ to avoid Rust keyword conflict
    pub n_chunks: i32,
    pub code_size: usize,
}

/// Per-op profiling accumulator (matches fuji_eval_profile in eval.h).
#[repr(C)]
pub struct fuji_eval_profile {
    pub op_counts: [u64; 11],
    pub op_ns: [u64; 11],
}

/// JIT-compiled chunk function pointer (matches jit_chunk_fn in jit.h).
/// Generated by fuji_jit_compile, called per chunk.
pub type jit_chunk_fn = unsafe extern "C" fn(
    chunk_start: i32,
    scratch: *mut fuji_field,
    out: *mut fuji_field,
    poly_table: *const fuji_eval_poly,
    scalars: *const fuji_field,
    omega: *const fuji_field,
    p: *const std::ffi::c_void,
    p_inv_lo: u64,
);

#[link(name = "fuji")]
extern "C" {
    /* ── Detection ─────────────────────────────────────────── */

    /// Returns `FUJI_OK` if the AMX coprocessor is available and enabled.
    pub fn fuji_detect_amx() -> i32;

    /// Writes the CPU generation enum (`FUJI_CPU_M1` = 1, etc.) to `*out`.
    pub fn fuji_detect_cpu(out: *mut i32) -> i32;

    /// Writes the AMX ISA version enum (`FUJI_AMX_V2` = 2, etc.) to `*out`.
    pub fn fuji_detect_amx_ver(out: *mut i32) -> i32;

    /// Returns a static null-terminated CPU brand string (e.g. `"Apple M4"`).
    /// Never NULL, never needs freeing.
    pub fn fuji_cpu_brand() -> *const c_char;

    /// Returns a static null-terminated library version string (`"0.1.0"`).
    pub fn fuji_lib_version() -> *const c_char;

    /// Returns non-zero if the SME (Scalable Matrix Extension) is available.
    /// SME is available on Apple M4 and later.
    pub fn fuji_sme_available() -> i32;

    /* ── Field ─────────────────────────────────────────────── */

    /// Writes the additive identity (zero) to `*out`.
    pub fn fuji_f_zero(out: *mut fuji_field) -> i32;

    /// Writes the multiplicative identity (one) to `*out`.
    pub fn fuji_f_one(out: *mut fuji_field) -> i32;

    /// Reads 32 little-endian bytes into `*out`. No reduction is performed;
    /// out-of-range values wrap modulo 2²⁵⁶ (caller must canonicalise).
    pub fn fuji_f_from_bytes(src: *const u8, out: *mut fuji_field) -> i32;

    /// Writes the canonical little-endian byte representation to `dst`.
    pub fn fuji_f_to_bytes(f: *const fuji_field, dst: *mut u8) -> i32;

    /// `*out = a + b mod p`  where `p` is the modulus for `curve`.
    pub fn fuji_f_add(a: *const fuji_field, b: *const fuji_field,
                      curve: fuji_curve, out: *mut fuji_field) -> i32;

    /// `*out = a - b mod p`.
    pub fn fuji_f_sub(a: *const fuji_field, b: *const fuji_field,
                      curve: fuji_curve, out: *mut fuji_field) -> i32;

    /// `*out = a * b mod p`. Uses AMX `matint` when available, scalar fallback otherwise.
    pub fn fuji_f_mul(a: *const fuji_field, b: *const fuji_field,
                      curve: fuji_curve, out: *mut fuji_field) -> i32;

    /// `*out = a * b mod p` using the scalar Montgomery path only.
    /// Bypasses AMX dispatch. Useful for benchmarking or comparison.
    pub fn fuji_f_mul_ref(a: *const fuji_field, b: *const fuji_field,
                          curve: fuji_curve, out: *mut fuji_field) -> i32;

    /// PRL (parallel) extension: returns non-zero if available.
    pub fn fuji_prl_available() -> i32;

    /// 2× parallel CIOS Montgomery field multiplication.
    pub fn fuji_f_mul_2x(a0: *const fuji_field, b0: *const fuji_field,
                          a1: *const fuji_field, b1: *const fuji_field,
                          curve: fuji_curve,
                          out0: *mut fuji_field, out1: *mut fuji_field) -> i32;

    /// 3× parallel CIOS Montgomery field multiplication.
    pub fn fuji_f_mul_3x(a0: *const fuji_field, b0: *const fuji_field,
                          a1: *const fuji_field, b1: *const fuji_field,
                          a2: *const fuji_field, b2: *const fuji_field,
                          curve: fuji_curve,
                          out0: *mut fuji_field, out1: *mut fuji_field,
                          out2: *mut fuji_field) -> i32;

    /// 4× parallel CIOS Montgomery field multiplication.
    pub fn fuji_f_mul_4x(a0: *const fuji_field, b0: *const fuji_field,
                          a1: *const fuji_field, b1: *const fuji_field,
                          a2: *const fuji_field, b2: *const fuji_field,
                          a3: *const fuji_field, b3: *const fuji_field,
                          curve: fuji_curve,
                          out0: *mut fuji_field, out1: *mut fuji_field,
                          out2: *mut fuji_field, out3: *mut fuji_field) -> i32;

    // ── Batch field ops (Mont-form) ──

    /// Element-wise multiply n pairs. Mont-form in/out.
    pub fn fuji_f_mul_batch(a: *const fuji_field, b: *const fuji_field,
                             out: *mut fuji_field, n: i32, curve: fuji_curve) -> i32;

    /// Element-wise add n pairs. Mont-form in/out.
    pub fn fuji_f_add_batch(a: *const fuji_field, b: *const fuji_field,
                             out: *mut fuji_field, n: i32, curve: fuji_curve) -> i32;

    /// Element-wise sub n pairs. Mont-form in/out.
    pub fn fuji_f_sub_batch(a: *const fuji_field, b: *const fuji_field,
                             out: *mut fuji_field, n: i32, curve: fuji_curve) -> i32;

    /// Element-wise scale by scalar. Mont-form in/out.
    pub fn fuji_f_scale_batch(a: *const fuji_field, s: *const fuji_field,
                               out: *mut fuji_field, n: i32, curve: fuji_curve) -> i32;

    /// 4× batch mixed addition — single FFI call, zero Rust add/sub crossing.
    pub fn fuji_f_point_add_mixed_batch_4(
        a0: *const fuji_point, b0: *const fuji_affine,
        a1: *const fuji_point, b1: *const fuji_affine,
        a2: *const fuji_point, b2: *const fuji_affine,
        a3: *const fuji_point, b3: *const fuji_affine,
        curve: fuji_curve,
        out0: *mut fuji_point, out1: *mut fuji_point,
        out2: *mut fuji_point, out3: *mut fuji_point) -> i32;

    /// Bucket reduction: 256 Mont-form buckets → 1 winsum (single FFI call).
    pub fn fuji_f_bucket_reduce_256(buckets: *const fuji_point,
                                     curve: fuji_curve,
                                     winsum: *mut fuji_point) -> i32;

    /// Window combination: 32 Mont-form winsums → result (single FFI call).
    pub fn fuji_f_combine_windows_32(winsum: *const fuji_point,
                                      curve: fuji_curve,
                                      out: *mut fuji_point) -> i32;

    /// Combined fill + reduce for one window (signed, single FFI call).
    /// Interprets window byte as int8_t; negates base Y for negative values.
    /// Bucket array must have at least 129 entries (indices 0..128).
    pub fn fuji_f_signed_fill_reduce_window(sbytes: *const u8,
                                             bases: *const fuji_affine,
                                             n: i32, win: i32, curve: fuji_curve,
                                             buckets: *mut fuji_point,
                                             winsum: *mut fuji_point) -> i32;

    /// Combined fill + reduce for one window (unsigned, single FFI call).
    /// Bucket array must have at least 256 entries (indices 0..255).
    pub fn fuji_f_fill_reduce_window(sbytes: *const u8,
                                      bases: *const fuji_affine,
                                      n: i32, win: i32, curve: fuji_curve,
                                      buckets: *mut fuji_point,
                                      winsum: *mut fuji_point) -> i32;

    /// Batch-4 PRL Pippenger MSM: 4 independent MSMs in parallel via work-stealing.
    pub fn fuji_f_prl_pippenger_batch_4(
        scalars: *const u8,
        bases: *const fuji_affine,
        n: i32, curve: fuji_curve,
        out: *mut fuji_point) -> i32;

    /// Identical-G fast-path batch-4 MSM: 4 × n scalars, single base.
    ///
    /// Uses table lookup (k×G precompute) instead of per-scalar bucket fill.
    /// `base` must be in normal-form affine coordinates.
    pub fn fuji_validate_mbb_header(hdr: *const u8) -> i32;

    pub fn fuji_f_msm_fixed_batch_4(
        scalars: *const u8,
        base: *const fuji_affine,
        n: i32, curve: fuji_curve,
        out: *mut fuji_point) -> i32;

    /// `*out = a² mod p`. Optimised wrapper around [`fuji_f_mul`].
    pub fn fuji_f_sqr(a: *const fuji_field, curve: fuji_curve,
                      out: *mut fuji_field) -> i32;

    /// `*out = a⁻¹ mod p`  (Fermat inversion: `a^(p-2)`).
    pub fn fuji_f_inv(a: *const fuji_field, curve: fuji_curve,
                      out: *mut fuji_field) -> i32;

    /// `*out = sqrt(a) mod p` if `a` is a quadratic residue, else returns a non-square root.
    pub fn fuji_f_sqrt(a: *const fuji_field, curve: fuji_curve,
                       out: *mut fuji_field) -> i32;

    /// Convert normal form to Montgomery form: a_mont = a * R mod p.
    pub fn fuji_field_to_mont(a: *const fuji_field, a_mont: *mut fuji_field,
                               curve: fuji_curve);

    /// Convert Montgomery form to normal form: a = a_mont * R^(-1) mod p.
    pub fn fuji_field_from_mont(a_mont: *const fuji_field, a: *mut fuji_field,
                                 curve: fuji_curve);

    /// Returns non-zero if `a == b`, zero otherwise.
    pub fn fuji_f_eq(a: *const fuji_field, b: *const fuji_field) -> i32;

    /// Batch multiply: `out[i] = a[i] * b[i]` for `i in 0..n`.
    /// All pointer arguments must point to at least `n` elements.
    pub fn fuji_field_batch_mul(a: *const fuji_field, b: *const fuji_field,
                                n: i32, curve: fuji_curve,
                                out: *mut fuji_field) -> i32;

    /// Batch square: `out[i] = a[i]²` for `i in 0..n`.
    pub fn fuji_field_batch_sqr(a: *const fuji_field, n: i32,
                                curve: fuji_curve,
                                out: *mut fuji_field) -> i32;

    /* ── Curve points ──────────────────────────────────────── */

    /// Writes the Pallas generator `(-1, 2)` to `*out`.
    pub fn fuji_gen_pallas(out: *mut fuji_affine) -> i32;

    /// Writes the Vesta generator `(-1, 2)` to `*out`.
    pub fn fuji_gen_vesta(out: *mut fuji_affine) -> i32;

    /// Converts an affine point to Jacobian coordinates (`Z = 1`).
    pub fn fuji_pt_from_affine(a: *const fuji_affine, curve: fuji_curve,
                               out: *mut fuji_point) -> i32;

    /// Writes the identity point (`Z = 0`) to `*out`.
    pub fn fuji_pt_id(out: *mut fuji_point) -> i32;

    /// Returns non-zero if `*p` is the identity (`Z == 0`).
    pub fn fuji_pt_is_id(p: *const fuji_point) -> i32;

    /// `*out = 2·p`  (Jacobian doubling for the `a = 0` curve).
    pub fn fuji_pt_double(p: *const fuji_point, curve: fuji_curve,
                          out: *mut fuji_point) -> i32;

    /// `*out = p + q`  (general Jacobian–Jacobian addition).
    pub fn fuji_pt_add(p: *const fuji_point, q: *const fuji_point,
                       curve: fuji_curve, out: *mut fuji_point) -> i32;

    /// `*out = p + q`  where `q` is affine (mixed addition, ~25% faster).
    pub fn fuji_pt_add_mixed(p: *const fuji_point, q: *const fuji_affine,
                             curve: fuji_curve, out: *mut fuji_point) -> i32;

    /// `*out = -p`  (negate Y, keep X and Z).
    pub fn fuji_pt_negate(p: *const fuji_point, curve: fuji_curve,
                          out: *mut fuji_point) -> i32;

    /// Converts a Jacobian point to affine: `x = X/Z²`, `y = Y/Z³`.
    /// Identity maps to `(0, 0)`.
    pub fn fuji_pt_to_affine(p: *const fuji_point, curve: fuji_curve,
                             out: *mut fuji_affine) -> i32;

    /// Batch negate: `out[i] = -in[i]` for `i in 0..n`.
    pub fn fuji_pt_batch_negate(ptr: *const fuji_point, n: i32,
                                curve: fuji_curve,
                                out: *mut fuji_point) -> i32;

    /// Batch Jacobian-to-affine conversion.
    pub fn fuji_pt_batch_to_affine(ptr: *const fuji_point, n: i32,
                                   curve: fuji_curve,
                                   out: *mut fuji_affine) -> i32;

    /* ── MSM ───────────────────────────────────────────────── */

    /// Single multi-scalar multiplication: `*out = Σ₀ⁿ⁻¹ scalars[i] · bases[i]`.
    ///
    /// Uses Pippenger's bucket method. Both slices must be exactly `n` elements long.
    /// Returns `FUJI_ERR_OOM` if allocation fails.
    pub fn fuji_msm_eval(bases: *const fuji_affine,
                         scalars: *const fuji_field,
                         n: i32, curve: fuji_curve,
                         out: *mut fuji_point) -> i32;

    /// Batch MSM: executes `n_msms` independent MSMs using concatenated `bases` and `scalars`.
    ///
    /// `counts[i]` specifies how many (scalar, base) pairs the `i`-th MSM consumes.
    /// `sum(counts)` must equal the length of `bases` and `scalars`.
    /// Writes `n_msms` output points to `*out`.
    pub fn fuji_msm_batch(counts: *const i32, n_msms: i32,
                          bases: *const fuji_affine,
                          scalars: *const fuji_field,
                          curve: fuji_curve,
                          out: *mut fuji_point) -> i32;

    /// Precomputes Pippenger window tables for a fixed base. Subsequent
    /// [`fuji_msm_fixed_batch`] calls with the same base reuse the table.
    pub fn fuji_msm_fixed_precompute(base: *const fuji_affine,
                                     curve: fuji_curve) -> i32;

    /// Fixed-base batch MSM: `out[i] = Σ scalars[j] · base` for each window.
    pub fn fuji_msm_fixed_batch(scalars: *const fuji_field,
                                counts: *const i32, n_msms: i32,
                                base: *const fuji_affine,
                                curve: fuji_curve,
                                out: *mut fuji_point) -> i32;

    /* ── Streaming MSM ─────────────────────────────────────── */

    /// Allocates a streaming MSM state for `n_total` pairs.
    /// `*out` must be freed with [`fuji_msm_stream_free`] if not finalized.
    pub fn fuji_msm_stream_new(st: *mut *mut fuji_msm_stream,
                               n_total: i32, curve: fuji_curve) -> i32;

    /// Feeds `n` (scalar, base) pairs into the streaming MSM state.
    /// May be called multiple times; total fed must not exceed `n_total`.
    pub fn fuji_msm_stream_feed(st: *mut fuji_msm_stream,
                                bases: *const fuji_affine,
                                scalars: *const fuji_field,
                                n: i32) -> i32;

    /// Finalizes the streaming MSM, writes the result to `*out`, and frees the state.
    /// The handle is invalid after this call.
    pub fn fuji_msm_stream_finalize(st: *mut fuji_msm_stream,
                                    out: *mut fuji_point) -> i32;

    /// Frees a streaming MSM state without finalizing.
    pub fn fuji_msm_stream_free(st: *mut fuji_msm_stream);

    /* ── SRS batch MSM ──────────────────────────────────────── */

    /// Precompute SRS: allocate buffers for batch MSM processing.
    pub fn fuji_f_srs_precompute(bases: *const fuji_affine, n: i32,
                                  curve: fuji_curve) -> *mut fuji_srs_ctx;

    /// Commit to many polynomials in a single batch call.
    pub fn fuji_f_srs_commit_batch(ctx: *mut fuji_srs_ctx,
                                    scalars: *const fuji_field,
                                    n_polys: i32, n: i32,
                                    out: *mut fuji_point) -> i32;

    /// Free a precomputed SRS context.
    pub fn fuji_f_srs_free(ctx: *mut fuji_srs_ctx);

    /* ── NTT ───────────────────────────────────────────────── */

    /// In-place NTT over `n` field elements. `n` must be a power of two ≤ 2¹⁶.
    /// `invert = 0` → forward NTT, `invert = 1` → inverse NTT.
    pub fn fuji_ntt(a: *mut fuji_field, n: i32, curve: fuji_curve,
                    invert: i32) -> i32;

    /// Batch NTT: `count` independent transforms of `n` elements each.
    /// `a` must point to `n * count` elements.
    pub fn fuji_ntt_batch(a: *mut fuji_field, n: i32, count: i32,
                          curve: fuji_curve, invert: i32) -> i32;

    /* ── Flat instruction evaluator ──────────────────────────── */

    /// Execute a compiled instruction sequence for one chunk.
    /// `profile` can be NULL to skip profiling.
    pub fn fuji_eval_execute(
        code: *const fuji_eval_instr, n_instr: i32,
        poly_table: *const fuji_eval_poly, n_polys: i32,
        scalars: *const fuji_field, n_scalars: i32,
        scratch: *mut fuji_field, n_rows: i32,
        chunk_start: i32, chunk_len: i32,
        omega: *const fuji_field,
        curve: fuji_curve,
        out: *mut fuji_field,
        profile: *mut fuji_eval_profile,
    );

    /* ── Lifecycle ──────────────────────────────────────────── */

    /// Restores signal handlers and frees library-global state.
    /// Safe to call multiple times; idempotent.
    pub fn fuji_cleanup_ffi();

    /* ── MAP_JIT SVE2 Compiler ───────────────────────────────── */

    /// Compile bytecode to native ARM64/SVE2 code in a MAP_JIT buffer.
    /// Returns a function pointer. Caller must call `fuji_jit_free` when done.
    pub fn fuji_jit_compile(
        code: *const fuji_eval_instr, n_instr: i32,
        poly_table: *const fuji_eval_poly, n_polys: i32,
        chunk_len: i32, n_rows: i32,
        curve: fuji_curve,
    ) -> jit_chunk_fn;

    /// Free a JIT-compiled function buffer previously returned by `fuji_jit_compile`.
    pub fn fuji_jit_free(fn_ptr: jit_chunk_fn);

    /// Return the compiled code size in bytes (valid after `fuji_jit_compile`).
    pub fn fuji_jit_code_size() -> usize;

    /// Create a clone in a new MAP_JIT buffer. Caller must free with `fuji_jit_free`.
    pub fn fuji_jit_clone(fn_ptr: jit_chunk_fn, code_size: usize) -> jit_chunk_fn;

    /// Batch-clone into N pre-allocated MAP_JIT buffers under ONE write-protect toggle.
    /// The caller must mmap N dst buffers with MAP_JIT (RO|WX) FIRST.
    /// Copies code into each buffer with a single pthread_jit_write_protect_np(0/1) pair.
    /// Returns 0 on success, -1 on error.
    pub fn fuji_jit_batch_clone(
        src: jit_chunk_fn,
        code_size: usize,
        dst_bufs: *mut jit_chunk_fn,
        n: i32,
    ) -> i32;

    /// Return the modulus pointer for a given curve (Pallas or Vesta).
    pub fn fuji_field_modulus(curve: fuji_curve) -> *const u8;

    /// Convenience: compile JIT from a deserialized bytecode handle.
    pub fn fuji_jit_compile_from_bc(bc: *const fuji_bytecode) -> jit_chunk_fn;

    /// Extract the initial scalar array from a deserialized bytecode.
    /// `out_n` receives the number of scalars. Returned pointer is valid
    /// until `fuji_bytecode_free`.
    pub fn fuji_jit_bytecode_scalars(bc: *const fuji_bytecode, out_n: *mut i32) -> *const fuji_field;

    /* ── JIT bench API ───────────────────────────────────────── */

    /// Zero-alloc dispatch: caller pre-allocates per-chunk buffers.
    pub fn fuji_jit_dispatch(
        fn_ptr: jit_chunk_fn,
        num_chunks: i32, chunk_len: i32,
        scs: *mut *mut fuji_field,
        outs: *mut *mut fuji_field,
        poly_table: *const fuji_eval_poly,
        scalars: *const fuji_field,
        omega: *const fuji_field,
        p: *const std::ffi::c_void,
        p_inv_lo: u64,
    );

    pub fn fuji_jit_bench(
        code: *const fuji_eval_instr, n_instr: i32,
        poly_table: *const fuji_eval_poly, n_polys: i32,
        scalars: *const fuji_field, n_scalars: i32,
        omega: *const fuji_field,
        curve: fuji_curve,
        chunk_len: i32, max_depth: i32,
        n: i32, n_threads: i32,
    ) -> fuji_jit_bench_t;

    /// Execute a pre-compiled JIT with external scalars (no compilation, no verify).
    pub fn fuji_jit_bench_exec(
        fn_ptr: jit_chunk_fn,
        code: *const fuji_eval_instr, n_instr: i32,
        poly_table: *const fuji_eval_poly, n_polys: i32,
        scalars: *const fuji_field, n_scalars: i32,
        omega: *const fuji_field,
        curve: fuji_curve,
        chunk_len: i32, max_depth: i32,
        n: i32, n_threads: i32,
    ) -> fuji_jit_bench_t;

    /// Single FFI call: compile (cached) + dispatch + return results.
    /// cache: [in/out] *cache = NULL → compiles + allocates, stores handle.
    ///        Pass same pointer to reuse JIT + buffers (no alloc, no compile).
    pub fn fuji_jit_eval(
        bc: *const fuji_bytecode,
        scalars: *const fuji_field, n_scalars: i32,
        output: *mut fuji_field,
        cache: *mut *mut std::ffi::c_void,
        n_threads: i32,
    ) -> fuji_jit_bench_t;

    /// Free the evaluation cache (JIT fn + pre-allocated buffers).
    pub fn fuji_jit_cache_free(cache: *mut std::ffi::c_void);

    /// Single-call eval from raw bytecode buffer (no cache, no subprocess).
    /// Parses bytecode, compiles JIT, dispatches all chunks, writes results.
    /// Returns 0 on success, -1 on error.
    pub fn fuji_jit_eval_from_buf(
        bc_buf: *const u8, bc_len: usize,
        scalars: *const fuji_field,
        results: *mut fuji_field,
    ) -> i32;

    /// Two-phase eval: compile from raw bytecode buffer, returns cache handle.
    /// Caller must free with `fuji_jit_cache_free`.
    pub fn fuji_jit_compile_from_buf(
        bc_buf: *const u8, bc_len: usize,
    ) -> *mut std::ffi::c_void;

    /// Two-phase eval: dispatch with new scalars using cached JIT (no re-compile).
    /// Returns 0 on success, -1 on error.
    pub fn fuji_jit_eval_cached(
        cache: *mut std::ffi::c_void,
        scalars: *const fuji_field,
        results: *mut fuji_field,
    ) -> i32;

    /// Two-phase eval like [`fuji_jit_eval_cached`] but uses a caller-provided
    /// poly table instead of the bytecode's embedded one. Permutation/lookup
    /// product polys are recomputed per prove round, so callers must inject the
    /// current round's table. Returns 0 on success, -1 on error.
    pub fn fuji_jit_eval_cached_poly(
        cache: *mut std::ffi::c_void,
        poly_table: *const fuji_eval_poly, n_polys: i32,
        scalars: *const fuji_field,
        results: *mut fuji_field,
    ) -> i32;

    /* ── Bytecode serialization ───────────────────────────────── */

    pub fn fuji_bytecode_size(
        code: *const fuji_eval_instr, n_instr: i32,
        poly_table: *const fuji_eval_poly, n_polys: i32,
        scalars: *const fuji_field, n_scalars: i32,
        omega: *const fuji_field,
        curve: fuji_curve,
        chunk_len: i32, max_depth: i32,
    ) -> usize;

    pub fn fuji_bytecode_write(
        code: *const fuji_eval_instr, n_instr: i32,
        poly_table: *const fuji_eval_poly, n_polys: i32,
        scalars: *const fuji_field, n_scalars: i32,
        omega: *const fuji_field,
        curve: fuji_curve,
        chunk_len: i32, max_depth: i32,
        buf: *mut u8, buf_len: usize,
    ) -> i32;

    pub fn fuji_bytecode_read(
        buf: *const u8, buf_len: usize,
        out: *mut *mut fuji_bytecode,
    ) -> i32;

    pub fn fuji_bytecode_free(bc: *mut fuji_bytecode);
}
